import { Mission } from './types';

export const MISSIONS: Mission[] = [
  // ═══════════════════════════════════════════════════════════════
  // EXPLORER TRACK — Week 1
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'explorer-w1-1',
    title: 'Wake Up Robo!',
    emoji: '🌅',
    week: 1,
    track: 'explorer',
    description: 'Wake up your robot friend! Tap the button to open Robo\'s eyes and say good morning!',
    shortDescription: 'Tap to wake up Robo!',
    concepts: ['cause-and-effect', 'sequencing'],
    color: 'from-yellow-300 to-orange-400',
    activity: {
      type: 'tap',
      requiredTaps: 3,
      successMessage: 'Robo is awake! Great job! 🌟',
      buttons: [
        { id: 'wake', emoji: '☀️', label: 'Wake Up!', action: { action: 'wake_up' }, color: 'bg-yellow-400 hover:bg-yellow-500' },
        { id: 'blink', emoji: '👁️', label: 'Blink!', action: { action: 'blink', params: { count: 3 } }, color: 'bg-orange-400 hover:bg-orange-500' },
        { id: 'happy', emoji: '😊', label: 'Be Happy!', action: { action: 'express', params: { emotion: 'happy' } }, color: 'bg-green-400 hover:bg-green-500' },
      ],
    },
    badge: {
      id: 'early-bird',
      title: 'Early Bird!',
      emoji: '🐦',
      description: 'You woke up Robo for the first time!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Wake Up Stretch',
      description: 'Just like Robo, do a big morning stretch! Reach your arms up high, then wiggle your fingers. Can you blink your eyes really fast 3 times?',
      emoji: '🤸',
      duration: '5 min',
    },
  },
  {
    id: 'explorer-w1-2',
    title: 'Happy Dance!',
    emoji: '💃',
    week: 1,
    track: 'explorer',
    description: 'Make Robo do a happy dance! Tap the dance buttons to teach Robo your best moves!',
    shortDescription: 'Tap to make Robo dance!',
    concepts: ['sequencing', 'patterns', 'cause-and-effect'],
    color: 'from-pink-400 to-purple-400',
    activity: {
      type: 'tap',
      requiredTaps: 4,
      successMessage: 'Robo danced! You\'re amazing! 🕺',
      buttons: [
        { id: 'dance-happy', emoji: '🕺', label: 'Happy Dance!', action: { action: 'dance', params: { style: 'happy' } }, color: 'bg-pink-400 hover:bg-pink-500' },
        { id: 'dance-robot', emoji: '🤖', label: 'Robot Dance!', action: { action: 'dance', params: { style: 'robot' } }, color: 'bg-purple-400 hover:bg-purple-500' },
        { id: 'wave', emoji: '👋', label: 'Wave!', action: { action: 'wave', params: { hand: 'right' } }, color: 'bg-blue-400 hover:bg-blue-500' },
        { id: 'excited', emoji: '🤩', label: 'So Excited!', action: { action: 'express', params: { emotion: 'excited' } }, color: 'bg-yellow-400 hover:bg-yellow-500' },
      ],
    },
    badge: {
      id: 'dance-star',
      title: 'Dance Star!',
      emoji: '⭐',
      description: 'You made Robo dance!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Copy My Dance',
      description: 'Take turns being the robot! One person does a move, the other copies it exactly. Wave your right arm, then your left. Nod your head. Spin around!',
      emoji: '🎵',
      duration: '10 min',
    },
  },
  {
    id: 'explorer-w1-3',
    title: 'Wave Hello!',
    emoji: '👋',
    week: 1,
    track: 'explorer',
    description: 'Teach Robo to say hello to everyone! Tap each wave button and see what Robo does.',
    shortDescription: 'Tap to make Robo wave!',
    concepts: ['cause-and-effect', 'communication'],
    color: 'from-blue-300 to-teal-400',
    activity: {
      type: 'sequence',
      description: 'Do these moves in order to teach Robo to say hello!',
      steps: [
        { emoji: '👋', label: 'Wave Right', action: { action: 'wave', params: { hand: 'right' } } },
        { emoji: '🤚', label: 'Wave Left', action: { action: 'wave', params: { hand: 'left' } } },
        { emoji: '😊', label: 'Smile', action: { action: 'express', params: { emotion: 'happy' } } },
        { emoji: '🗣️', label: 'Say Hi', action: { action: 'speak', params: { text: 'Hello friend! Nice to meet you!' } } },
      ],
    },
    badge: {
      id: 'friendly-robot',
      title: 'Friendly Robot!',
      emoji: '🤝',
      description: 'You taught Robo to wave hello!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Hello in Every Language',
      description: 'Teach each other how to say hello in different ways: wave, bow, high five, fist bump! Can you think of 3 different ways robots might say hello?',
      emoji: '🌍',
      duration: '5 min',
    },
  },
  {
    id: 'explorer-w1-4',
    title: 'Robo Feelings',
    emoji: '😊',
    week: 1,
    track: 'explorer',
    description: 'Robots have feelings too! Tap the emoji to make Robo feel that way!',
    shortDescription: 'Match Robo\'s feelings!',
    concepts: ['emotions', 'communication', 'cause-and-effect'],
    color: 'from-green-300 to-emerald-400',
    activity: {
      type: 'tap',
      requiredTaps: 5,
      successMessage: 'Robo can show all the feelings! 🌈',
      buttons: [
        { id: 'happy', emoji: '😊', label: 'Happy', action: { action: 'express', params: { emotion: 'happy' } }, color: 'bg-yellow-400 hover:bg-yellow-500' },
        { id: 'sad', emoji: '😢', label: 'Sad', action: { action: 'express', params: { emotion: 'sad' } }, color: 'bg-blue-400 hover:bg-blue-500' },
        { id: 'excited', emoji: '🤩', label: 'Excited', action: { action: 'express', params: { emotion: 'excited' } }, color: 'bg-orange-400 hover:bg-orange-500' },
        { id: 'thinking', emoji: '🤔', label: 'Thinking', action: { action: 'express', params: { emotion: 'thinking' } }, color: 'bg-purple-400 hover:bg-purple-500' },
        { id: 'surprised', emoji: '😲', label: 'Surprised', action: { action: 'express', params: { emotion: 'surprised' } }, color: 'bg-pink-400 hover:bg-pink-500' },
      ],
    },
    badge: {
      id: 'emotion-explorer',
      title: 'Emotion Explorer!',
      emoji: '💝',
      description: 'You helped Robo feel all the feelings!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Feelings Charades',
      description: 'Make a face showing an emotion — the other person guesses what feeling it is! Happy, sad, surprised, excited, tired, confused...',
      emoji: '🎭',
      duration: '10 min',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // EXPLORER TRACK — Week 2
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'explorer-w2-1',
    title: 'Look Around!',
    emoji: '👀',
    week: 2,
    track: 'explorer',
    description: 'Help Robo look in all directions! Tap the arrows to move Robo\'s head!',
    shortDescription: 'Help Robo look around!',
    concepts: ['directions', 'spatial-awareness'],
    color: 'from-cyan-300 to-blue-400',
    activity: {
      type: 'tap',
      requiredTaps: 4,
      successMessage: 'Robo saw everything! 🌟',
      buttons: [
        { id: 'left', emoji: '⬅️', label: 'Look Left', action: { action: 'look', params: { direction: 'left' } }, color: 'bg-cyan-400 hover:bg-cyan-500' },
        { id: 'right', emoji: '➡️', label: 'Look Right', action: { action: 'look', params: { direction: 'right' } }, color: 'bg-blue-400 hover:bg-blue-500' },
        { id: 'up', emoji: '⬆️', label: 'Look Up', action: { action: 'look', params: { direction: 'up' } }, color: 'bg-indigo-400 hover:bg-indigo-500' },
        { id: 'down', emoji: '⬇️', label: 'Look Down', action: { action: 'look', params: { direction: 'down' } }, color: 'bg-violet-400 hover:bg-violet-500' },
      ],
    },
    badge: {
      id: 'explorer-eyes',
      title: 'Eagle Eyes!',
      emoji: '🦅',
      description: 'You helped Robo look all around!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Direction Game',
      description: 'Play Simon Says with directions! "Look left... look right... look up... spin around!" One person is the robot, the other gives commands.',
      emoji: '🧭',
      duration: '5 min',
    },
  },
  {
    id: 'explorer-w2-2',
    title: 'Simon Says Robo!',
    emoji: '🎮',
    week: 2,
    track: 'explorer',
    description: 'Can you copy Robo\'s moves? Watch what Robo does, then tap the same button!',
    shortDescription: 'Copy Robo\'s moves!',
    concepts: ['memory', 'patterns', 'sequencing'],
    color: 'from-purple-300 to-pink-400',
    activity: {
      type: 'simon',
      description: 'Robo will do some moves. Then you copy the same moves in the same order!',
      sequence: [
        { action: 'wave', params: { hand: 'right' } },
        { action: 'look', params: { direction: 'left' } },
        { action: 'express', params: { emotion: 'happy' } },
        { action: 'nod' },
      ],
    },
    badge: {
      id: 'memory-master',
      title: 'Memory Master!',
      emoji: '🧠',
      description: 'You remembered Robo\'s whole sequence!',
      rarity: 'rare',
    },
    unpluggedActivity: {
      title: 'Robot Memory Chain',
      description: 'Build a sequence together! Person 1 does a move. Person 2 copies it and adds one more. Keep going! How long can the chain get?',
      emoji: '🔗',
      duration: '10 min',
    },
  },
  {
    id: 'explorer-w2-3',
    title: 'Robo Song!',
    emoji: '🎵',
    week: 2,
    track: 'explorer',
    description: 'Help Robo make music! Tap the buttons to make Robo sing and move to the beat!',
    shortDescription: 'Make Robo sing!',
    concepts: ['patterns', 'rhythm', 'sequencing'],
    color: 'from-orange-300 to-red-400',
    activity: {
      type: 'sequence',
      description: 'Tap the buttons in order to make Robo perform a song!',
      steps: [
        { emoji: '🎵', label: 'Sing La!', action: { action: 'speak', params: { text: 'La la la!' } } },
        { emoji: '💃', label: 'Dance Move', action: { action: 'dance', params: { style: 'wave' } } },
        { emoji: '👋', label: 'Wave Arms', action: { action: 'wave', params: { hand: 'right' } } },
        { emoji: '🎵', label: 'Sing Again!', action: { action: 'speak', params: { text: 'Do re mi fa sol!' } } },
        { emoji: '🤩', label: 'Take a Bow!', action: { action: 'express', params: { emotion: 'excited' } } },
      ],
    },
    badge: {
      id: 'music-maker',
      title: 'Music Maker!',
      emoji: '🎸',
      description: 'You made Robo perform a song!',
      rarity: 'rare',
    },
    unpluggedActivity: {
      title: 'Make a Robot Song',
      description: 'Invent a silly robot song together! Use clapping, stomping, and humming. Make robot sounds: beep boop! Can you make a 4-beat rhythm and repeat it?',
      emoji: '🎶',
      duration: '10 min',
    },
  },
  {
    id: 'explorer-w2-4',
    title: 'Bedtime Robo!',
    emoji: '🌙',
    week: 2,
    track: 'explorer',
    description: 'Robo is tired! Help Robo get ready for sleep with a bedtime routine.',
    shortDescription: 'Help Robo go to sleep!',
    concepts: ['sequencing', 'routines', 'cause-and-effect'],
    color: 'from-indigo-400 to-purple-500',
    activity: {
      type: 'sequence',
      description: 'Do Robo\'s bedtime routine in the right order!',
      steps: [
        { emoji: '😴', label: 'Feel Sleepy', action: { action: 'express', params: { emotion: 'sleepy' } } },
        { emoji: '👀', label: 'Look Down', action: { action: 'look', params: { direction: 'down' } } },
        { emoji: '💤', label: 'Sleep!', action: { action: 'sleep' } },
        { emoji: '🌙', label: 'Goodnight!', action: { action: 'speak', params: { text: 'Goodnight! Sweet dreams!' } } },
      ],
    },
    badge: {
      id: 'night-watcher',
      title: 'Night Watcher!',
      emoji: '🌟',
      description: 'You helped Robo have a great bedtime routine!',
      rarity: 'rare',
    },
    unpluggedActivity: {
      title: 'Robot Bedtime Story',
      description: 'Invent a bedtime story about a tired robot! What adventures did it have today? How does it charge up for tomorrow? Take turns adding parts to the story.',
      emoji: '📖',
      duration: '10 min',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // BUILDER TRACK — Week 1
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'builder-w1-1',
    title: 'First Command',
    emoji: '🚀',
    week: 1,
    track: 'builder',
    description: 'Write your first robot command! Drag blocks to make Robo wave hello.',
    shortDescription: 'Make Robo wave with code blocks',
    concepts: ['commands', 'sequencing', 'input-output'],
    color: 'from-blue-400 to-indigo-500',
    activity: {
      type: 'blockly',
      challenge: 'Make Robo wave with the right hand, then smile!',
      availableBlocks: ['robot_wave', 'robot_express', 'robot_speak'],
      expectedSequence: ['wave', 'express'],
      hint: 'Try the "Wave" block first, then add an "Express" block set to "happy"!',
    },
    badge: {
      id: 'first-coder',
      title: 'First Coder!',
      emoji: '💻',
      description: 'You wrote your first robot command!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Human Robot Commands',
      description: 'Write commands on paper for a "human robot". Example: "Wave right arm → Smile → Say hello". Then follow the commands exactly. What happens if you change the order?',
      emoji: '📝',
      duration: '15 min',
    },
  },
  {
    id: 'builder-w1-2',
    title: 'Say Hello!',
    emoji: '💬',
    week: 1,
    track: 'builder',
    description: 'Program Robo to greet people! Use the Say block to make Robo speak.',
    shortDescription: 'Program Robo to speak',
    concepts: ['output', 'strings', 'sequencing'],
    color: 'from-teal-400 to-cyan-500',
    activity: {
      type: 'blockly',
      challenge: 'Make Robo say "Hello!" then wave, then say "Nice to meet you!"',
      availableBlocks: ['robot_speak', 'robot_wave', 'robot_express', 'robot_look'],
      expectedSequence: ['speak', 'wave', 'speak'],
      hint: 'Use 2 "Say" blocks and 1 "Wave" block. Put them in the right order!',
    },
    badge: {
      id: 'chatty-programmer',
      title: 'Chatty Programmer!',
      emoji: '🗣️',
      description: 'You made Robo say hello!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Conversation Flowchart',
      description: 'Draw a flowchart of a conversation! Box 1: "Say hello" → Box 2: "Wave" → Box 3: "Ask a question". Can you draw arrows showing the order?',
      emoji: '📊',
      duration: '15 min',
    },
  },
  {
    id: 'builder-w1-3',
    title: 'Move & Look',
    emoji: '👀',
    week: 1,
    track: 'builder',
    description: 'Control Robo\'s head movement with code! Try looking in different directions.',
    shortDescription: 'Control Robo\'s head with code',
    concepts: ['parameters', 'directions', 'sequencing'],
    color: 'from-purple-400 to-pink-500',
    activity: {
      type: 'blockly',
      challenge: 'Make Robo look left, then right, then center, then nod!',
      availableBlocks: ['robot_look', 'robot_nod', 'robot_wave', 'robot_express'],
      expectedSequence: ['look', 'look', 'look', 'nod'],
      hint: 'Use 3 "Look" blocks with different directions, then a "Nod" block!',
    },
    badge: {
      id: 'head-controller',
      title: 'Head Controller!',
      emoji: '🎯',
      description: 'You mastered head movement commands!',
      rarity: 'common',
    },
    unpluggedActivity: {
      title: 'Coordinate Grid',
      description: 'Draw a grid on paper. Label directions: up, down, left, right, center. Give your partner coordinates to move to, like a robot! Can you make a path across the grid?',
      emoji: '🗺️',
      duration: '15 min',
    },
  },
  {
    id: 'builder-w1-4',
    title: 'Debug It!',
    emoji: '🐛',
    week: 1,
    track: 'builder',
    description: 'Something is wrong with this robot program! Find the bug and fix it.',
    shortDescription: 'Fix the broken robot program',
    concepts: ['debugging', 'logic', 'problem-solving'],
    color: 'from-red-400 to-orange-500',
    activity: {
      type: 'debug',
      description: 'This program should make Robo say hello then wave. But it\'s backwards! Can you fix it?',
      brokenCode: [
        { action: 'wave', params: { hand: 'right' } },
        { action: 'speak', params: { text: 'Hello!' } },
      ],
      hint: 'Robots should say hello BEFORE waving, just like people do!',
      correctSequence: [
        { action: 'speak', params: { text: 'Hello!' } },
        { action: 'wave', params: { hand: 'right' } },
      ],
    },
    badge: {
      id: 'bug-hunter',
      title: 'Bug Hunter!',
      emoji: '🔍',
      description: 'You found and fixed your first bug!',
      rarity: 'rare',
    },
    unpluggedActivity: {
      title: 'Broken Recipe',
      description: 'Write a recipe with the steps scrambled (make sandwich: put bread on plate, add filling, butter bread, eat). Can you put them in the right order? This is exactly what debugging is!',
      emoji: '🥪',
      duration: '10 min',
    },
  },

  // ═══════════════════════════════════════════════════════════════
  // BUILDER TRACK — Week 2
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'builder-w2-1',
    title: 'Repeat Magic',
    emoji: '🔁',
    week: 2,
    track: 'builder',
    description: 'Loops let you repeat commands without writing them multiple times! Make Robo wave 3 times.',
    shortDescription: 'Use loops to make Robo dance',
    concepts: ['loops', 'repetition', 'efficiency'],
    color: 'from-blue-500 to-violet-500',
    activity: {
      type: 'blockly',
      challenge: 'Make Robo wave 3 times using a REPEAT block (not 3 separate wave blocks!)',
      availableBlocks: ['robot_wave', 'robot_express', 'controls_repeat', 'robot_speak'],
      expectedSequence: ['wave', 'wave', 'wave'],
      hint: 'Use a "Repeat 3 times" block and put ONE wave block inside it. Much cleaner than writing wave 3 times!',
    },
    badge: {
      id: 'loop-master',
      title: 'Loop Master!',
      emoji: '🔄',
      description: 'You used loops to repeat commands!',
      rarity: 'rare',
    },
    unpluggedActivity: {
      title: 'Loop Dance',
      description: 'Choreograph a dance with a loop! Write: "Repeat 4 times: clap, clap, stomp, spin". How does using a loop make it easier to write down the dance?',
      emoji: '💫',
      duration: '10 min',
    },
  },
  {
    id: 'builder-w2-2',
    title: 'If-Then Power',
    emoji: '⚡',
    week: 2,
    track: 'builder',
    description: 'Conditionals let robots make decisions! Make Robo react differently based on what happens.',
    shortDescription: 'Make Robo react with conditions',
    concepts: ['conditionals', 'decision-making', 'logic'],
    color: 'from-yellow-500 to-orange-500',
    activity: {
      type: 'blockly',
      challenge: 'Make a program: if Robo is happy → dance, otherwise → wave',
      availableBlocks: ['robot_wave', 'robot_dance', 'robot_express', 'controls_if', 'robot_speak'],
      expectedSequence: ['express', 'dance'],
      hint: 'Use an "If...Do...Else" block. Set Robo to happy first, then let the program decide what to do!',
    },
    badge: {
      id: 'decision-maker',
      title: 'Decision Maker!',
      emoji: '🧠',
      description: 'You made Robo make decisions!',
      rarity: 'rare',
    },
    unpluggedActivity: {
      title: 'Robot Decision Tree',
      description: 'Draw a decision tree: "Is it raining? YES → get umbrella → go outside. NO → just go outside." Make your own tree for a robot deciding what to do on different days!',
      emoji: '🌳',
      duration: '15 min',
    },
  },
  {
    id: 'builder-w2-3',
    title: 'Build a Sequence',
    emoji: '📋',
    week: 2,
    track: 'builder',
    description: 'Chain many commands together to build a complete robot routine! Design your own sequence.',
    shortDescription: 'Chain commands together',
    concepts: ['sequencing', 'algorithms', 'design'],
    color: 'from-green-500 to-teal-500',
    activity: {
      type: 'blockly',
      challenge: 'Build a 5-step morning greeting routine for Robo! Must include: wake up, look around, say good morning, wave, and express happiness.',
      availableBlocks: ['robot_wave', 'robot_wake_up', 'robot_look', 'robot_speak', 'robot_express', 'robot_nod', 'robot_dance'],
      expectedSequence: ['wake_up', 'look', 'speak', 'wave', 'express'],
      hint: 'Think about what order makes sense. What do YOU do when you wake up?',
    },
    badge: {
      id: 'sequence-builder',
      title: 'Sequence Builder!',
      emoji: '🏗️',
      description: 'You built a complete robot routine!',
      rarity: 'rare',
    },
    unpluggedActivity: {
      title: 'Algorithm for Getting Ready',
      description: 'Write down every single step for getting ready for school — don\'t skip anything! "Wake up → open eyes → sit up → put feet on floor → stand up..." How many steps did you count?',
      emoji: '📝',
      duration: '15 min',
    },
  },
  {
    id: 'builder-w2-4',
    title: 'Grand Challenge',
    emoji: '🏆',
    week: 2,
    track: 'builder',
    description: 'The ultimate test! Build a full performance routine using loops, sequences, and all your skills!',
    shortDescription: 'Complete a full robot performance',
    concepts: ['loops', 'sequencing', 'algorithms', 'creativity'],
    color: 'from-amber-500 to-yellow-400',
    activity: {
      type: 'blockly',
      challenge: 'Create a 10-command performance using at least 1 loop, a greeting, a dance, and an ending. This is your graduation show!',
      availableBlocks: ['robot_wave', 'robot_dance', 'robot_speak', 'robot_express', 'robot_look', 'robot_wake_up', 'robot_nod', 'controls_repeat'],
      expectedSequence: ['wave', 'dance', 'speak'],
      hint: 'Start with a greeting, build to a climax with a loop, end with a goodbye! Make it spectacular!',
    },
    badge: {
      id: 'grand-champion',
      title: 'Grand Champion!',
      emoji: '🥇',
      description: 'You completed the Week 2 Grand Challenge!',
      rarity: 'legendary',
    },
    unpluggedActivity: {
      title: 'Perform Your Algorithm',
      description: 'Act out the program you just wrote! You be the robot, your parent/sibling reads the blocks aloud one by one, and you execute each command. Film it if you want!',
      emoji: '🎬',
      duration: '15 min',
    },
  },
];

export function getMissionsByTrack(track: 'explorer' | 'builder'): Mission[] {
  return MISSIONS.filter(m => m.track === track);
}

export function getMissionsByWeek(track: 'explorer' | 'builder', week: number): Mission[] {
  return MISSIONS.filter(m => m.track === track && m.week === week);
}

export function getMissionById(id: string): Mission | undefined {
  return MISSIONS.find(m => m.id === id);
}
